name: Coba Akses Secret Environment

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-secret:
    runs-on: ubuntu-latest
    environment: secretsaya  # penting! harus sesuai dengan environment tempat secret berada

    steps:
      - name: Print secret (untuk testing — hindari di production!)
        run: echo "Nilai SECRET_SATU adalah: ${{ secrets.SECRET_SATU }}"
