name: Debug Secret

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  debug-secret:
    runs-on: ubuntu-latest
    environment: secretsaya

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate random filename and create markdown
        env:
          SECRET_SATU: ${{ secrets.SECRET_SATU }}
        run: |
          mkdir -p notes
          FILENAME="notes/note-$(openssl rand -hex 4).md"
          DATE=$(date +"%Y-%m-%d %H:%M:%S")
          echo "$SECRET_SATU" > "$FILENAME"
          echo "File created: $FILENAME"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Menambahkan file markdown acak baru"
          git push
        
